name: Postman Collection Run

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  postman-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Postman CLI
        run: |
          run: curl -o- "https://dl-cli.pstmn-beta.io/install/unix.sh" | sh

      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}

      - name: Run API Quality Score Service collection
        run: |
          postman collection run "1110081-abc03db5-abb6-448f-b10a-a3280d930938" \
            -e "1109466-25f7c205-0bbe-4a25-b78c-7806c396e274"
